project:
  type: website
  output-dir: docs

website:
  title: "Youtube Demo Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Favorites.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

